### ISSUE TITLE
Wrong password checks

### ISSUE THREAD

**Issue by valid22** [widd/kitsune#12]
ref: https://github.com/widd/kitsune/blob/master/Kitsune/ClubPenguin/Login.php#L38
Shouldn't it be checking ```$encryptedPassword ``` instead of ```$penguinData["Password"]```

**Comment by rushilsrivastava** [comment]
It should be checking `$encryptedPassword`. May have been intended to include encrypted password into the `$penguinData` array.

**Comment by valid22** [comment]
@rushilsrivastava PHP knows basic salt hashing, but it doesn't know the hash process Kitsune does.

**Comment by Baysul** [comment]
`$penguinData["Password"]` is correct. The value of `$password` is the output of `getLoginHash` from the client,  and the database value is the [password_hash](https://secure.php.net/manual/en/function.password-hash.php) output of the `getLoginHash` function.

So basically, `$penguinData["Password"]` is ``password_hash(getLoginHash(..))``.

The way [password_verify ](https://secure.php.net/manual/en/function.password-verify.php)works is that it takes the plain-text version of the password as the first argument and compares it to the second, which is a `password_hash` string.

The [handleRandomKey](https://github.com/widd/kitsune/blob/master/Kitsune/ClubPenguin/ClubPenguin.php#L215) function and the [registration script](https://github.com/widd/kitsune-register/blob/master/src/register.php#L27) might need adjustments though so that the static key is consistent.

Currently the registration script uses `e4a2dbcca10a7246817a83cd` as the static key, but the server sends `"e4a2dbcca10a7246817a83cd" . $penguin->username;`

**Comment by valid22** [comment]
@TunnelBlanket Sounds like the problem with register. But you cannot expect everyone to use same register script.

**Comment by widd** [comment]
Fixed in widd/kitsune-register@bbce10c
